"""empty message

Revision ID: 37a1210ae960
Revises: a872407e5fee
Create Date: 2017-03-03 10:27:21.483462

"""

# revision identifiers, used by Alembic.
revision = '37a1210ae960'
down_revision = 'a872407e5fee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('contact_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conference', 'contact_number')
    # ### end Alembic commands ###
