"""empty message

Revision ID: 69937a5d68db
Revises: 8c53a8c2a8c9
Create Date: 2016-12-08 11:53:18.273000

"""

# revision identifiers, used by Alembic.
revision = '69937a5d68db'
down_revision = '8c53a8c2a8c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('conference', sa.Column('arrivingtime', sa.DateTime(), nullable=True))
    op.add_column('conference', sa.Column('conftime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conference_arrivingtime'), 'conference', ['arrivingtime'], unique=False)
    op.create_index(op.f('ix_conference_conftime'), 'conference', ['conftime'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conference_conftime'), table_name='conference')
    op.drop_index(op.f('ix_conference_arrivingtime'), table_name='conference')
    op.drop_column('conference', 'conftime')
    op.drop_column('conference', 'arrivingtime')
    op.drop_column('conference', 'address')
    ### end Alembic commands ###
