"""empty message

Revision ID: 9a61406ca127
Revises: 69937a5d68db
Create Date: 2016-12-23 11:23:14.318000

"""

# revision identifiers, used by Alembic.
revision = '9a61406ca127'
down_revision = '69937a5d68db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('fee', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conference', 'fee')
    ### end Alembic commands ###
