"""empty message

Revision ID: a872407e5fee
Revises: 9a61406ca127
Create Date: 2016-12-26 10:40:02.819000

"""

# revision identifiers, used by Alembic.
revision = 'a872407e5fee'
down_revision = '9a61406ca127'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatarUrl', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('dep', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('nickName', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('province', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'province')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'nickName')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'dep')
    op.drop_column('users', 'city')
    op.drop_column('users', 'avatarUrl')
    ### end Alembic commands ###
